# fly.toml app configuration file generated for fullstack-boilerplate on 2025-03-24T11:42:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-boilerplate'
primary_region = 'fra'

[build]

[env]
  PLT_SERVER_HOSTNAME = '0.0.0.0'
  PLT_SERVER_LOGGER_LEVEL = 'info'
  PLT_TYPESCRIPT = 'false'
  PORT = '3402'

[[mounts]]
  source = 'data'
  destination = '/app/.platformatic/data'

[http_service]
  internal_port = 3042
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
