alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: platformatic-example
    match:
      path:
        prefix: /
name: example
region: fra
services:
- dockerfile_path: /Dockerfile
  github:
    branch: main
    repo: Akallabet/platformatic-example
  http_port: 3042
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: platformatic-example
  source_dir: /
